# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brady Watkinson dot com
tagline:          'A personal website'
description:      'This is my personal website where I post about projects, ideas and general tech stuff'
url:              http://github.com/bradywatkinson
baseurl:          https://www.bradywatkinson.com

author:
  name:           'Brady Watkinson'
  url:            https://twitter.com/bradywatkinson

gems: [jekyll-paginate]
paginate:         5


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bradywatkinson/bradywatkinson.github.io

slack:
  link:           http://slack.bradywatkinson.com
